spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}

storage:
  bucket: ${STORAGE_BUCKET}
  endpoint: ${STORAGE_ENDPOINT}
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173