spring:
  application:
    name: pelada-api

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: Pelada API
    version: 1.0.0
    description: API para organização de partidas e contratação de goleiros.

jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}